name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  prepare-dataset:
    uses: ./.github/workflows/prepare-dataset.yml

  run-tests:
    runs-on: ubuntu-latest
    needs: prepare-dataset

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download dataset
        uses: actions/cache@v3
        with:
          path: datasets.zip
          key: dataset-zip
      - name: Unzip dataset
        run: unzip ./datasets.zip -d ${GITHUB_WORKSPACE}/trabalho-pratico/datasets
      - name: Run tests
        run: cd trabalho-pratico && make test